apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurence-eta-app-deploy
  labels:
    app: insurence-eta-app-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurence-eta-app
  template:
    metadata:
      labels:
        app: insurence-eta-app
    spec:
      containers:
      - name: insurence-eta-container
        image: bsvk38/insurence-eta-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insurence-eta-np-service
  labels:
    app: insurence-eta-app
spec:
  selector:
    app: insurence-eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31030
    port: 8080
    targetPort: 8083
